#!/usr/bin/env python3
"""
Simple PDF creator using basic Python libraries.
Creates text-based reports that can be converted to PDF.
"""

import os
from datetime import datetime

def create_text_report(incident_data, filename):
    """Create a detailed text report that can be converted to PDF."""
    
    report_content = f"""
================================================================================
                        INCIDENT INVESTIGATION REPORT
================================================================================

Report ID: {incident_data.get('id', 'Unknown')}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Status: {incident_data.get('status', 'Unknown')}
Classification: Official Investigation Report

================================================================================
                              INCIDENT DETAILS
================================================================================

Date of Incident:     {incident_data.get('date', 'Unknown')}
Time of Incident:     {incident_data.get('time', 'Unknown')}
Location:             {incident_data.get('location', 'Unknown')}
Incident Type:        {incident_data.get('incident_type', 'Unknown')}
Reporting Officer:    {incident_data.get('reporting_officer', 'Unknown')}
Evidence:             {incident_data.get('evidence', 'Unknown')}

"""

    # Add victims section if available
    if 'victims' in incident_data and incident_data['victims']:
        report_content += """
================================================================================
                                  VICTIMS
================================================================================

"""
        for i, victim in enumerate(incident_data['victims']):
            report_content += f"""
Victim {i+1}:
    Name:     {victim.get('name', 'Unknown')}
    Age:      {victim.get('age', 'Unknown')}
    Gender:   {victim.get('gender', 'Unknown')}
    Injuries: {victim.get('injuries', 'Unknown')}

"""

    # Add suspects section if available
    if 'suspects' in incident_data and incident_data['suspects']:
        report_content += """
================================================================================
                                 SUSPECTS
================================================================================

"""
        for i, suspect in enumerate(incident_data['suspects']):
            report_content += f"""
Suspect {i+1}:
    Name:        {suspect.get('name', 'Unknown')}
    Age:         {suspect.get('age', 'Unknown')}
    Gender:      {suspect.get('gender', 'Unknown')}
    Description: {suspect.get('description', 'Unknown')}

"""

    # Add description section
    if 'description' in incident_data and incident_data['description']:
        report_content += f"""
================================================================================
                            INCIDENT DESCRIPTION
================================================================================

{incident_data['description']}

"""

    # Add AI analysis section
    if 'ai_analysis' in incident_data and incident_data['ai_analysis']:
        report_content += f"""
================================================================================
                               AI ANALYSIS
================================================================================

{incident_data['ai_analysis']}

"""

    # Add footer
    report_content += f"""
================================================================================
                                 FOOTER
================================================================================

Generated by: AI Justice Grid Investigation System
Timestamp:    {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Report Type:  Automated Investigation Report
Confidentiality: Official Use Only

================================================================================
                              END OF REPORT
================================================================================
"""

    # Write to file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    return True

def create_sample_reports():
    """Create sample text reports."""
    
    # Sample incident data
    incidents = [
        {
            "id": "INC-0001",
            "date": "2025-01-16",
            "time": "13:43",
            "location": "Public Transit Station, Platform 2",
            "incident_type": "Trespassing",
            "description": "Incident reported at 13:43 on 2025-01-16. Witness reported suspicious activity involving an individual who gained unauthorized access to restricted areas of the public transit station. Security footage shows the suspect bypassing security barriers and entering maintenance areas.",
            "reporting_officer": "Officer Susan Thompson",
            "victims": [
                {
                    "name": "Michael Thompson",
                    "age": 73,
                    "gender": "Male",
                    "injuries": "Moderate bruising on left arm and shoulder"
                }
            ],
            "suspects": [
                {
                    "name": "Unknown Individual",
                    "age": 33,
                    "gender": "Non-binary",
                    "description": "Masked individual wearing dark clothing, approximately 5'8\" tall, medium build"
                }
            ],
            "evidence": "Digital security camera recordings, witness statements, physical evidence at scene",
            "status": "Closed",
            "ai_analysis": "Based on the evidence collected and witness statements, this trespassing incident appears to involve a masked individual who gained unauthorized access to public transit property. The moderate injuries sustained by the victim suggest a physical altercation occurred during the confrontation. The digital records provide crucial evidence for identifying the suspect. The case has been closed following successful identification and apprehension of the perpetrator through security footage analysis."
        },
        {
            "id": "MURDER-001",
            "date": "2025-01-15",
            "time": "23:30",
            "location": "789 Elm Street, Apartment 3C, Downtown District",
            "incident_type": "Homicide Investigation",
            "description": "Victim found deceased in living room of apartment 3C with multiple stab wounds to the chest. Scene shows signs of struggle with overturned furniture and broken items. No signs of forced entry, suggesting victim knew the perpetrator. Kitchen knife found at scene appears to be the murder weapon.",
            "reporting_officer": "Detective Sarah Johnson",
            "victims": [
                {
                    "name": "Robert Johnson",
                    "age": 42,
                    "gender": "Male",
                    "injuries": "Multiple stab wounds to chest and abdomen - Fatal injuries"
                }
            ],
            "suspects": [
                {
                    "name": "Lisa Johnson (Ex-wife)",
                    "age": 38,
                    "gender": "Female",
                    "description": "5'6\" tall, brown hair, last seen wearing dark clothing. Has documented history of threats against victim following recent divorce proceedings."
                },
                {
                    "name": "David Chen (Business Partner)",
                    "age": 45,
                    "gender": "Male",
                    "description": "5'10\" tall, black hair, wears glasses. Currently involved in financial dispute with victim over company assets and profit sharing."
                }
            ],
            "evidence": "Bloody kitchen knife (murder weapon), fingerprints on door handle and knife, victim's cell phone with recent threatening text messages, blood spatter analysis, broken glass from struggle, witness statements from neighbors",
            "status": "Under Investigation",
            "ai_analysis": "This homicide investigation reveals several key findings suggesting a crime of passion rather than premeditation. The lack of forced entry strongly indicates the victim knew their attacker and willingly allowed them access. The kitchen knife used as the murder weapon was obtained from the victim's own kitchen, suggesting the violence escalated during a confrontation rather than being planned. Timeline analysis shows the victim arrived home at 22:45, with the argument beginning around 23:00 and escalating to violence by 23:30 - a 45-minute window indicating prolonged confrontation. The ex-wife emerges as the primary suspect due to multiple factors: documented history of threats, recent financial motive from will changes, and familiarity with the victim's residence and habits. The business partner remains a secondary suspect pending further investigation into the financial dispute. Forensic priorities include expedited fingerprint analysis on the murder weapon, DNA analysis of blood evidence, and comprehensive cell phone data analysis. Investigation recommendations: 1) Immediate questioning of ex-wife with legal counsel present, 2) Financial audit of business partnership, 3) Neighborhood canvas for additional witnesses, 4) Search warrants for suspect residences and vehicles."
        }
    ]
    
    # Create output directory
    output_dir = "generated_reports"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    print("Generating text-based investigation reports...")
    print("=" * 60)
    
    for incident in incidents:
        filename = os.path.join(output_dir, f"incident_report_{incident['id']}.txt")
        
        success = create_text_report(incident, filename)
        if success:
            print(f"✓ Generated report: {filename}")
            # Get file size
            file_size = os.path.getsize(filename)
            print(f"  File size: {file_size} bytes")
        else:
            print(f"✗ Failed to generate: {filename}")
    
    print("=" * 60)
    print(f"✓ Successfully generated {len(incidents)} investigation reports")
    print(f"✓ Reports saved in '{output_dir}' directory")
    print("\nThese text reports can be:")
    print("1. Opened in any text editor")
    print("2. Converted to PDF using online converters")
    print("3. Printed directly from text editors")
    print("4. Used as templates for formal reports")

if __name__ == "__main__":
    create_sample_reports()
